name: Kegenix
favicon: null
layout_spectrum: 0.39553376706317067
typography_spectrum: 0.4051513122394681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#175177'
    - '#398ead'
    - '#8194a1'
    - '#a5b8c3'
  brandStrength: 0.7128489271271974
  lightness: 0.7040853856597096
  saturation: 0.5970595688559115
  rhythmicContrast: 0.9312473316676915
purpose: []
